### ISSUE TITLE
Custom compilation v1.0.17 - Provider crashes

### ISSUE THREAD

**Issue by edouardpodvin** [aiven/terraform-provider-aiven#108]
I compiled the provider in version 1.0.17, 
with go v1.12.7   and    v1.12.6
with terraform v0.11.14

The compilation is successful, however, when using the provider in another environment, terraform crashes the same way as in this issue : https://github.com/aiven/terraform-provider-aiven/issues/92
```
Error: Error asking for user input: 1 error occurred:
	* module.aiven_services.provider.aiven: plugin exited before we could connect




panic: Failed to read service_user_config_schema.json: stat /home/vagrant/test_aiven/templates/service_user_config_schema.json: no such file or directory
2019-11-27T15:13:54.216Z [DEBUG] plugin.terraform-provider-aiven_v1.0.17: 
2019-11-27T15:13:54.216Z [DEBUG] plugin.terraform-provider-aiven_v1.0.17: goroutine 1 [running]:
2019-11-27T15:13:54.216Z [DEBUG] plugin.terraform-provider-aiven_v1.0.17: github.com/aiven/terraform-provider-aiven/aiven.readUserConfigJSONSchema(0x11472d3, 0x1f, 0x112cb2f)
2019-11-27T15:13:54.216Z [DEBUG] plugin.terraform-provider-aiven_v1.0.17: 	/home/jenkins/agent/workspace/terraform_CICD_master/src/github.com/aiven/terraform-provider-aiven/aiven/user_config.go:17 +0x317
2019-11-27T15:13:54.216Z [DEBUG] plugin.terraform-provider-aiven_v1.0.17: github.com/aiven/terraform-provider-aiven/aiven.GetUserConfigSchema(0x112cb2f, 0x7, 0x1134e0c)
2019-11-27T15:13:54.216Z [DEBUG] plugin.terraform-provider-aiven_v1.0.17: 	/home/jenkins/agent/workspace/terraform_CICD_master/src/github.com/aiven/terraform-provider-aiven/aiven/user_config.go:41 +0x1a0
2019-11-27T15:13:54.216Z [DEBUG] plugin.terraform-provider-aiven_v1.0.17: github.com/aiven/terraform-provider-aiven/aiven.init.ializers()
2019-11-27T15:13:54.216Z [DEBUG] plugin.terraform-provider-aiven_v1.0.17: 	/home/jenkins/agent/workspace/terraform_CICD_master/src/github.com/aiven/terraform-provider-aiven/aiven/resource_service.go:139 +0x1f14

```

While trying to execute the provider in another environment that the one where it was compiled, it fails with following message:
```
./terraform-provider-aiven_v1.0.17 
panic: Failed to read service_user_config_schema.json: stat /home/vagrant/.terraform.d/plugins/temp/templates/service_user_config_schema.json: no such file or directory

goroutine 1 [running]:
github.com/aiven/terraform-provider-aiven/aiven.readUserConfigJSONSchema(0xf771d6, 0x1f, 0xf5f2af)
	/home/jenkins/agent/workspace/terraform_CICD_master/src/github.com/aiven/terraform-provider-aiven/aiven/user_config.go:17 +0x317
github.com/aiven/terraform-provider-aiven/aiven.GetUserConfigSchema(0xf5f2af, 0x7, 0xf67124)
	/home/jenkins/agent/workspace/terraform_CICD_master/src/github.com/aiven/terraform-provider-aiven/aiven/user_config.go:41 +0x1a0
github.com/aiven/terraform-provider-aiven/aiven.init.ializers()
	/home/jenkins/agent/workspace/terraform_CICD_master/src/github.com/aiven/terraform-provider-aiven/aiven/resource_service.go:139 +0x1f14
```

**Comment by mteiste** [comment]
Aiven terraform provider uses packr2 to include the schema json files into the binary. If you want to build your own version of the binaries the recommended way to do it is to
- clone the repository (outside the normal ~/go/src/github.com)
- run `make bootstrap` followed by `make bins`

alternatively (assuming linux as the target) the following sequence of commands will provide a binary that can be copied to an other environment
```
go get github.com/gobuffalo/packr/...
go mod vendor
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 packr2 build -mod=vendor -o terraform-provider-aiven .
```
