### ISSUE TITLE
panic: Error reading level state: strconv.ParseInt: parsing "9223372036854776000": value out of range

### ISSUE THREAD

**Issue by schlurp** [aiven/terraform-provider-aiven#1187]
## What happened?

When spinning up a `aiven_kafka` instance with a parameter `log_cleaner_max_compaction_lag_ms` set to the default value of 
`9223372036854775807`, see https://kafka.apache.org/26/documentation.html#message.timestamp.difference.max.ms, then the creation of the kafka service succeeds and the cluster in the console can be managed and parameters can be changed. However, upon running terraform a second time, it fails with 

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ReadResource request was cancelled.
╵

Stack trace from the terraform-provider-aiven_v4.3.0 plugin:

panic: Error reading level state: strconv.ParseInt: parsing "9223372036854776000": value out of range

goroutine 79 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0xc0000fd000, {0xc000ac7720, 0x1, 0x1}, 0x8?)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource_data.go:553 +0x328
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0xc0000fd000)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource_data.go:351 +0x393
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0xc0007a89a0, {{{0xf528e0?, 0xc00000e9f0?}}, {0xcea680?, 0xc00031d680?}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:599 +0x1c9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0001861b0, {0xf521e0?, 0xc0007dcf90?}, 0xc0006b05c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:587 +0x205
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0xf55798?, 0xc0001861b0?}}, {0xf521e0?, 0xc0007dcf90?}, 0xc0006b0440?)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5to6server/tf5to6server.go:105 +0x242
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadResource({0xc0007ddb00, 0xc0007ddb60, {0xc00082f1f0, 0x1, 0x1}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0000caf00, {0xf521e0?, 0xc0002d8780?}, 0xc00070c600)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:746 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xdac4c0?, 0xc0000caf00}, {0xf521e0, 0xc0002d8780}, 0xc000282000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:383 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0xf55000, 0xc0007da4e0}, 0xc000828360, 0xc0006c1a40, 0x14b2d10, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xde3
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0xf55000, 0xc0007da4e0}, 0xc000828360, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

Error: The terraform-provider-aiven_v4.3.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

## What did you expect to happen?

The expected behavior would be for terraform to run without any change.

## What else do we need to know?

Used terraform template

```
resource "aiven_kafka" "kafka" {
  project                 = var.aiven_project_name
  cloud_name              = var.cloud_name
  service_name            = var.service_name
  plan                    = "startup-2"
  maintenance_window_dow  = "sunday"
  maintenance_window_time = "18:30:00"
  termination_protection  = false

  kafka_user_config {
    kafka_version = "3.4"
    kafka_rest               = true
    kafka_rest_authorization = true
    schema_registry          = true
    ip_filter_string         = ["0.0.0.0/0"]

    kafka {
      log_cleaner_max_compaction_lag_ms         = 9223372036854775807
    }

    kafka_authentication_methods {
      certificate = true
    }
  }
}
```

Might be similar to 

* https://github.com/hashicorp/terraform/issues/31930
* https://github.com/yandex-cloud/terraform-provider-yandex/issues/190

**Comment by Serpentiel** [comment]
hey 👋 

thanks for reporting this, our team will investigate this and will get back to you soon :)

**Comment by Serpentiel** [comment]
hey 👋

this appears to be a backend bug, I have forwarded it to the relevant team :)

if this isn't getting resolved soon, we will be implementing a workaround on our side

**Comment by Serpentiel** [comment]
hey 👋 

upon further investigation, it appears to be a problem with `go-cty`, which is a dependency of Terraform itself

I'll forward it to Hashicorp :)

**Comment by schlurp** [comment]
Thanks for the feedback. Looking forward to the fix.

**Comment by Serpentiel** [comment]
hey, @schlurp! 👋

I've forwarded it to Hashicorp for additional investigation, you can watch for it over here: https://github.com/hashicorp/terraform-plugin-sdk/issues/1215

as a temporary fix I suggest to lower this value in your manifest file
