### ISSUE TITLE
Changing "ip_filter_object" results in Plugin error

### ISSUE THREAD

**Issue by TimsDevCorner** [aiven/terraform-provider-aiven#1572]
## What happened?

When updating the `ip_filter_object` (changing one and deleting 2 others) I do get an Plugin Error with the following output:
```
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aiven_v4.13.3 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 68 [running]:
github.com/aiven/terraform-provider-aiven/internal/schemautil/userconfig/apiconvert.itemToAPI({0xc0003a3738, 0x5}, {0xfd2d26, 0x6}, {0xc00082dd80, 0x4, 0x4}, {0xc000658a08, 0x13}, {0xe3f9e0, ...}, ...)
        github.com/aiven/terraform-provider-aiven/internal/schemautil/userconfig/apiconvert/toapi.go:233 +0x893
github.com/aiven/terraform-provider-aiven/internal/schemautil/userconfig/apiconvert.arrayItemToAPI({0xc0003a3738, 0x5}, {0xc00082dd80?, 0x3, 0x4}, {0xfd2d1c, 0x10}, {0xc0008d0000, 0x10, 0x10}, ...)
        github.com/aiven/terraform-provider-aiven/internal/schemautil/userconfig/apiconvert/toapi.go:131 +0x730
github.com/aiven/terraform-provider-aiven/internal/schemautil/userconfig/apiconvert.itemToAPI({0xc0003a3738, 0x5}, {0xc00026fa54, 0x5}, {0xc00082dd80, 0x3, 0x4}, {0xfd2d1c, 0x10}, {0xe3f9e0, ...}, ...)
        github.com/aiven/terraform-provider-aiven/internal/schemautil/userconfig/apiconvert/toapi.go:271 +0x4bf
github.com/aiven/terraform-provider-aiven/internal/schemautil/userconfig/apiconvert.propsToAPI({0xc0003a3738, 0x5}, {0xc00025ec40?, 0x2, 0x2}, 0xc000c92690, 0xc000ad4200?, 0xe4e920?, {0x117dd90, 0xc00066d080})
        github.com/aiven/terraform-provider-aiven/internal/schemautil/userconfig/apiconvert/toapi.go:410 +0x485
github.com/aiven/terraform-provider-aiven/internal/schemautil/userconfig/apiconvert.ToAPI(0x117cdd0?, {0xc0003a3738, 0x5}, {0x117dd90, 0xc00066d080})
        github.com/aiven/terraform-provider-aiven/internal/schemautil/userconfig/apiconvert/toapi.go:469 +0x1e8
github.com/aiven/terraform-provider-aiven/internal/schemautil.ResourceServiceUpdate({0x117e4a0, 0xc00022b9d0}, 0xc00066d080, {0xf779a0?, 0xc000718000?})
        github.com/aiven/terraform-provider-aiven/internal/schemautil/service.go:530 +0x84a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc00037b0a0, {0x117e3f8, 0xc000aa74d0}, 0xd?, {0xf779a0, 0xc000718000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:812 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00037b0a0, {0x117e3f8, 0xc000aa74d0}, 0xc000494ea0, 0xc00066ce00, {0xf779a0, 0xc000718000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:919 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000108e8, {0x117e3f8?, 0xc000aa7320?}, 0xc0004d25f0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xdbc
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x1185080?, 0xc0000108e8?}}, {0x117e3f8, 0xc000aa7320}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:37 +0x54
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x117e430?, {0x117e3f8?, 0xc000aa6840?}, 0xc0004d25a0)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0003dc320, {0x117e3f8?, 0xc000b83aa0?}, 0xc00022a380)
        github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov6/tf6server/server.go:845 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xf9e060?, 0xc0003dc320}, {0x117e3f8, 0xc000b83aa0}, 0xc00057d600, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b2e00, {0x117e3f8, 0xc000b839e0}, {0x1183c50, 0xc000007860}, 0xc000574a20, 0xc000884450, 0x183dd18, 0x0)
        google.golang.org/grpc@v1.61.0/server.go:1385 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0001b2e00, {0x1183c50, 0xc000007860}, 0xc000574a20)
        google.golang.org/grpc@v1.61.0/server.go:1796 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.61.0/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 40
        google.golang.org/grpc@v1.61.0/server.go:1040 +0x135

Error: The terraform-provider-aiven_v4.13.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

## What did you expect to happen?

I expected the Plugin to not crash and to update the corresponding ip filters.

## What else do we need to know?

I hope the Stack Trace is enough. If you need logs, tell me where to find them 😄
(Or anything else, i will try my best)

**Comment by eversC** [comment]
this is happening for us too on `v4.9.2`

as a side-note, we made the change directly in the Aiven UI, but the ip_filter rules there are immutable and IP addresses must be unique, so we had to remove those rules we wanted to update first before adding them back in (which broke network connectivity temporarily)

**Comment by Serpentiel** [comment]
Hey, @eversC! 👋

> our changes made via the UI also don't seem to be realised yet by the terraform provider, so we've got a perpetual diff

When using Terraform, this is an anti-pattern because Terraform is supposed to be able to guarantee the state of the resource, so we wouldn't recommend this approach, and also that's the reason of the diff that you're seeing.

However, as a temporary solution (because Terraform is broken), this is completely okay to use, and completely understandable as well.

**Comment by eversC** [comment]
hi @Serpentiel , that makes sense, thanks. How's this one progressing?

we're currently seeing Terraform apply operations fail as the provider attempts to apply the changes from the perpetual diff. This looks to be okay in that other unrelated changes we're making via the provider are applied okay, but it'd be good to have the overall Terraform apply operation succeed again

**Comment by Serpentiel** [comment]
Hey folks! 👋

We have just pushed a change which is supposed to fix the issue.

We will be releasing a new RC version of the provider shortly which is going to allow to check if the fix works or not.

**Comment by TimsDevCorner** [comment]
Hey @Serpentiel ,

thank you very much!
The new version doesn't throw the exception I mentioned above.
