### ISSUE TITLE
plugin crash on aiven_pg import

### ISSUE THREAD

**Issue by mm-supernice** [aiven/terraform-provider-aiven#1734]
## What happened?

While importing a aiven_pg resource into the state:
Error: The terraform-provider-aiven_v4.18.0 plugin crashed!

panic: interface conversion: interface {} is []string, not []interface {}

from debug log:
rpc error: code = Unavailable desc = error reading from server: EOF

## What did you expect to happen?

Not to crash

## What else do we need to know?

Resource Definition:

_Module:_
```
resource "aiven_pg" "timescaledb-001" {
  project      = var.project
  cloud_name   = var.cloud_name
  plan         = var.plan
  service_name = var.service_name

  pg_user_config {
    pg_version = 15          # Choose an available postgres version
    variant    = "timescale" # Do not forget to specify this variant
  }
}
```

_Module Call:_

```
module "aiven_timescale_db" {
  source              = "git@github.com:XXXXXXXXX?ref=XXXXX"
  project = var.timescale.project
  cloud_name = var.timescale.cloud_name
  service_name = var.timescale.service_name
  plan = var.timescale.plan
}
```

_Vars:_
```
variable "timescale" {
  type = map
  default = {
    project = "XXX-0000"
    cloud_name = "timescale-azure-northeurope"
    plan = "timescale-dev-only"
    service_name = "XXXXXXXXX-XXX-XXX"
  }
}
```

_Trace:_

```
tf import module.aiven_timescale_db.aiven_pg.timescaledb-001 XXXXXXXXXXXXX-XXXX/XXXXXXXXXXXXX-XXXX-XXXX
Acquiring state lock. This may take a few moments...
data.external.aws_ip_ranges: Reading...
module.aiven_timescale_db.aiven_pg.timescaledb-001: Importing from ID "XXXXXXXXXXXXX-XXXX/XXXXXXXXXXXXX-XXXX-XXXX"...
module.aiven_timescale_db.aiven_pg.timescaledb-001: Import prepared!
  Prepared aiven_pg for import
module.aiven_timescale_db.aiven_pg.timescaledb-001: Refreshing state... [id=XXXXXXXXXXXXX-XXXX/XXXXXXXXXXXXX-XXXX-XXXX]
data.external.aws_ip_ranges: Read complete after 1s [id=-]
SOME_UNRELATED_MODULE_REF Reading...
SOME_UNRELATED_MODULE_REF Reading...
SOME_UNRELATED_MODULE_REF Read complete after 0s [id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
SOME_UNRELATED_MODULE_REF Reading...
SOME_UNRELATED_MODULE_REF Reading...
SOME_UNRELATED_MODULE_REF Reading...
SOME_UNRELATED_MODULE_REF Reading...
SOME_UNRELATED_DATA_REF Reading...
SOME_UNRELATED_MODULE_REF Read complete after 0s [id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
SOME_UNRELATED_MODULE_REF Read complete after 0s [id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
SOME_UNRELATED_MODULE_REF Reading...
SOME_UNRELATED_MODULE_REF Read complete after 0s [id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
SOME_UNRELATED_MODULE_REF Reading...
SOME_UNRELATED_MODULE_REF Read complete after 0s [id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
SOME_UNRELATED_DATA_REF Read complete after 0s [id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
SOME_UNRELATED_DATA_REF Reading...
SOME_UNRELATED_MODULE_REF Read complete after 0s [id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
SOME_UNRELATED_DATA_REF Reading...
SOME_UNRELATED_DATA_REF Reading...
SOME_UNRELATED_DATA_REF Reading...
SOME_UNRELATED_DATA_REF Reading...
SOME_UNRELATED_MODULE_REF Read complete after 0s [id=/subscriptions/SOME_UNRELATED_AZURE_RESOURCE]
SOME_UNRELATED_DATA_REF Read complete after 0s [id=/subscriptions/SOME_UNRELATED_AZURE_RESOURCE]
SOME_UNRELATED_MODULE_REF Read complete after 0s [id=/subscriptions/SOME_UNRELATED_AZURE_RESOURCE]
SOME_UNRELATED_DATA_REF Read complete after 1s [id=/subscriptions/SOME_UNRELATED_AZURE_RESOURCE]
SOME_UNRELATED_DATA_REF Read complete after 4s [id=/subscriptions/SOME_UNRELATED_AZURE_RESOURCE]
SOME_UNRELATED_DATA_REF Still reading... [10s elapsed]
SOME_UNRELATED_DATA_REF Still reading... [10s elapsed]
SOME_UNRELATED_DATA_REF Read complete after 19s [id=/subscriptions/SOME_UNRELATED_AZURE_RESOURCE]
SOME_UNRELATED_DATA_REF Still reading... [20s elapsed]
SOME_UNRELATED_DATA_REF Read complete after 24s [id=/subscriptions/SOME_UNRELATED_AZURE_RESOURCE]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-aiven_v4.18.0 plugin:

panic: interface conversion: interface {} is []string, not []interface {}

goroutine 46 [running]:
github.com/aiven/terraform-provider-aiven/internal/sdkprovider/userconfig/converters.flattenAttr(0x1337c0de?, {0x1337c0de?, 0x1337c0de?})
	github.com/aiven/terraform-provider-aiven/internal/sdkprovider/userconfig/converters/converters.go:440 +0x1337c0de
github.com/aiven/terraform-provider-aiven/internal/sdkprovider/userconfig/converters.flattenObj(0x1337c0de, 0x1337c0de)
	github.com/aiven/terraform-provider-aiven/internal/sdkprovider/userconfig/converters/converters.go:402 +0x1337c0de
github.com/aiven/terraform-provider-aiven/internal/sdkprovider/userconfig/converters.flatten({0x1337c0de, 0x1337c0de}, {0x1337c0de, 0x1337c0de}, 0x1337c0de, 0x1337c0de)
	github.com/aiven/terraform-provider-aiven/internal/sdkprovider/userconfig/converters/converters.go:382 +0x1337c0de
github.com/aiven/terraform-provider-aiven/internal/sdkprovider/userconfig/converters.Flatten({0x1337c0de, 0x1337c0de}, {0x1337c0de, 0x1337c0de}, 0x1337c0de?, 0x1337c0de?)
	github.com/aiven/terraform-provider-aiven/internal/sdkprovider/userconfig/converters/converters.go:348 +0x1337c0de
github.com/aiven/terraform-provider-aiven/internal/schemautil.FlattenService(...)
	github.com/aiven/terraform-provider-aiven/internal/schemautil/service.go:948
github.com/aiven/terraform-provider-aiven/internal/schemautil.copyServicePropertiesFromAPIResponseToTerraform(0x1337c0de, 0x1337c0de, {0x1337c0de?, 0x1337c0de?, 0x1337c0de?}, {0x1337c0de
e660, 0x1337c0de})
	github.com/aiven/terraform-provider-aiven/internal/schemautil/service.go:666 +0x1337c0de
github.com/aiven/terraform-provider-aiven/internal/schemautil.ResourceServiceRead({0x1337c0de, 0x1337c0de}, 0x1337c0de, {0x1337c0de, 0x1337c0de})
	github.com/aiven/terraform-provider-aiven/internal/schemautil/service.go:335 +0x1337c0de
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1337c0de, {0x1337c0de, 0x1337c0de}, 0x1337c0de, {0x1337c0de, 0x1337c0de})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:823 +0x1337c0de
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1337c0de, {0x1337c0de, 0x1337c0de}, 0x1337c0de, {0x1337c0de, 0x1337c0de})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:1117 +0x1337c0de
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1337c0de, {0x1337c0de?, 0x1337c0de?}, 0x1337c0de)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:708 +0x1337c0de
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x1337c0de?, 0x1337c0de?}}, {0x1337c0de?, 0x1337c0de?}, 0x1337c0de?)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5to6server/tf5to6server.go:153 +0x1337c0de
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x1337c0de, {0x1337c0de?, 0x1337c0de?}, 0x1337c0de)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf6muxserver/mux_server_ReadResource.go:35 +0x1337c0de
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x1337c0de, {0x1337c0de?, 0x1337c0de?}, 0x1337c0de)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:784 +0x1337c0de
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x1337c0de, 0x1337c0de}, {0x1337c0de, 0x1337c0de}, 0x1337c0de, 0x1337c0de)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:482 +0x1337c0de
google.golang.org/grpc.(*Server).processUnaryRPC(0x1337c0de, {0x1337c0de, 0x1337c0de}, {0x1337c0de, 0x1337c0de}, 0x1337c0de, 0x1337c0de, 0x1337c0de, 0x1337c0de)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0x1337c0de
google.golang.org/grpc.(*Server).handleStream(0x1337c0de, {0x1337c0de, 0x1337c0de}, 0x1337c0de)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0x1337c0de
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x1337c0de
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 71
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x1337c0de

Error: The terraform-provider-aiven_v4.18.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by byashimov** [comment]
Hey. Thanks for the report. While I'm preparing the fix you can try to define `ip_filter_object` in the user config:

```hcl
pg_user_config {
    ip_filter_object {
        network = <your ip filter>
    }
}
```

I assume the service was created in the Console.
The fix will be released asap.

**Comment by byashimov** [comment]
Hey @mm-supernice! Great to hear you have found a way to solve the issue. The new version is released.
