### ISSUE TITLE
[V1.3.2] interface conversion: interface {} is []interface {}, not string

### ISSUE THREAD

**Issue by ADefossez-Zenika** [aiven/terraform-provider-aiven#263]
Hello,
I had the same issue than #247 so i was waiting on the new patch to fix this one.
Once released, i've downloaded v1.3.2 but have a "panic" at terraform plan / apply.

`2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: panic: interface conversion: interface {} is []interface {}, not string
2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: 
2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: goroutine 1 [running]:
2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: github.com/aiven/terraform-provider-aiven/aiven.generateTerraformUserConfigSchema(0xc0003c7540, 0x18, 0xc0004205d0, 0x1)
2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: 	/srv/jenkins/workspace/terraform-provider-aiven/aiven/user_config.go:67 +0xc6e
2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: github.com/aiven/terraform-provider-aiven/aiven.GenerateTerraformUserConfigSchema(0xc0004203c0, 0x6)
2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: 	/srv/jenkins/workspace/terraform-provider-aiven/aiven/user_config.go:21 +0x1af
2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: github.com/aiven/terraform-provider-aiven/aiven.generateTerraformUserConfigSchema(0xc0003b7e60, 0xd, 0xc0004203c0, 0x1)
2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: 	/srv/jenkins/workspace/terraform-provider-aiven/aiven/user_config.go:59 +0x330
2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: github.com/aiven/terraform-provider-aiven/aiven.GenerateTerraformUserConfigSchema(0xc000420300, 0xc000420090)
2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: 	/srv/jenkins/workspace/terraform-provider-aiven/aiven/user_config.go:21 +0x1af
2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: github.com/aiven/terraform-provider-aiven/aiven.init()
2020-07-21T16:43:24.906+0200 [DEBUG] plugin.terraform-provider-aiven_v1.3.2: 	/srv/jenkins/workspace/terraform-provider-aiven/aiven/resource_service.go:228 +0x6a5a
`

More, on logs, i see path that are not on my compter : /srv/jenkins/workspace etc.

Is there something i can do ?

**Comment by ivan-savciuc** [comment]
Hello,

Thanks for reporting that and sorry for inconveniences. 

I re-uploaded binaries everything should be back to normal now.

**Comment by ADefossez-Zenika** [comment]
Nice, seems to works, thank you ;)
