### ISSUE TITLE
Terraform crash when importing teams

### ISSUE THREAD

**Issue by rust84** [aiven/terraform-provider-aiven#479]
## Terraform version 

0.12.30
## Aiven provider version
 2.1.11

## what happened?

When trying to import an existing team I encountered the following error

```
Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range [1] with length 1
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: 
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: goroutine 81 [running]:
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: github.com/aiven/terraform-provider-aiven/aiven.splitResourceID2(...)
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: 	github.com/aiven/terraform-provider-aiven/aiven/provider.go:270
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: github.com/aiven/terraform-provider-aiven/aiven.resourceAccountTeamRead(0x1128a28, 0xc000505480, 0xc000541000, 0xeef340, 0xc00062ca20, 0x8bff5c, 0xe3c520, 0xc00068e000)
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: 	github.com/aiven/terraform-provider-aiven/aiven/resource_account_team.go:78 +0x752
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: github.com/aiven/terraform-provider-aiven/aiven.resourceAccountTeamState(0x1128a28, 0xc000505480, 0xc000541000, 0xeef340, 0xc00062ca20, 0x1, 0x30, 0x7f5972dad108, 0x30, 0xc0004cbef0)
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: 	github.com/aiven/terraform-provider-aiven/aiven/resource_account_team.go:133 +0x65
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ImportState(0xc00008e0a0, 0x1128a28, 0xc000505480, 0xc00064faa8, 0xc00011b210, 0x4, 0x203000, 0x203000, 0x203000, 0x0, ...)
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/provider.go:367 +0x178
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ImportResourceState(0xc00054a648, 0x1128a28, 0xc000505480, 0xc0000aa960, 0xc000505480, 0xf133c0, 0xc0004cbc00)
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/grpc_provider.go:1021 +0xe5
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ImportResourceState(0xc0008aaa20, 0x1128ad0, 0xc000505480, 0xc0005440f0, 0xc0008aaa20, 0xc0004cbce0, 0xc00091cba0)
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:349 +0xdc
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ImportResourceState_Handler(0xf133c0, 0xc0008aaa20, 0x1128ad0, 0xc0004cbce0, 0xc0005374a0, 0x0, 0x1128ad0, 0xc0004cbce0, 0xc0001a50e0, 0x1a)
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:398 +0x214
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b6540, 0x11316b8, 0xc000103500, 0xc0000f9d00, 0xc000796600, 0x163e3b8, 0x0, 0x0, 0x0)
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: 	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: google.golang.org/grpc.(*Server).handleStream(0xc0000b6540, 0x11316b8, 0xc000103500, 0xc0000f9d00, 0x0)
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: 	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00011a130, 0xc0000b6540, 0x11316b8, 0xc000103500, 0xc0000f9d00)
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: 	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-13T12:42:02.882+0100 [DEBUG] plugin.terraform-provider-aiven_v2.1.11: 	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
2021/04/13 12:42:02 [ERROR] <root>: eval: *terraform.EvalImportState, err: rpc error: code = Unavailable desc = transport is closing
2021-04-13T12:42:02.884+0100 [DEBUG] plugin: plugin process exited: path=/home/russell/.terraform.d/plugins/terraform-provider-aiven_v2.1.11 pid=1417889 error="exit status 2"
2021/04/13 12:42:02 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/04/13 12:42:02 [TRACE] [walkImport] Exiting eval tree: aiven_account_team.test (import id "test")
2021/04/13 12:42:02 [TRACE] vertex "aiven_account_team.test (import id \"test\")": visit complete
2021-04-13T12:42:02.884+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/04/13 12:42:02 [TRACE] dag/walk: upstream of "provider.aiven (close)" errored, so skipping
2021-04-13T12:42:02.884+0100 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

## How to reproduce

I created a team named test

`avn account team list xxxxx`

```
ACCOUNT_ID    CREATE_TIME           TEAM_ID        TEAM_NAME       UPDATE_TIME         
============  ====================  =============  ==============  ====================
xxxx  2021-04-13T09:40:24Z  xxxx  Account Owners  2021-04-13T09:40:24Z
xxxx  2021-04-13T11:40:52Z  at326a7d7d772  test            2021-04-13T11:40:52Z
```

Created the resource in Terraform

```
resource "aiven_account_team" "test" {
    account_id = aiven_account.actual.account_id
    name = "test"
}
```

Ran the command to import

```
terraform import aiven_account_team.test at326a7d7d772
```

Terraform crashed.

**Comment by ivan-savciuc** [comment]
@rust84 to import `aiven_account_team` please use the following format for the ID: `<account_id>/<team_id>`, I'll update docs with that.
