### ISSUE TITLE
Terraform provider plugin crashes without meaningful error message

### ISSUE THREAD

**Issue by MojoJojo** [aiven/terraform-provider-aiven#539]
Hi,

I have the following terraform code:

```
resource "aiven_project" "aiven_project_kafka" {
  project = local.kafka_project_name
  account_id = var.aiven_account_id
  copy_from_project = "rxxxxxx"  
}
resource "aiven_kafka" "aiven_kafka_service_region_one" {
  project                = aiven_project.aiven_project_kafka.project
  cloud_name             = local.kafka_cloud_region_one
  plan                   = var.plan
  service_name           = local.kafka_region_one_service_name
  termination_protection = false
  project_vpc_id         = aiven_project_vpc.aiven_project_vpc_kafka_region_one.id



  kafka_user_config {
    kafka_version   = "2.8"
    kafka_rest      = "true"
    schema_registry = true
    kafka_connect   = false
    kafka {
      auto_create_topics_enable = false
    }
    # Set this to IP addresses from the peer
    ip_filter = []
    public_access {
      kafka_rest    = false
      kafka_connect = false
      prometheus    = false
    }
  }
}
resource "aiven_project_vpc" "aiven_project_vpc_kafka_region_one" {
  project      = aiven_project.aiven_project_kafka.project
  cloud_name   = local.kafka_cloud_region_one
  network_cidr = "10.0.0.0/16"
}
resource "aiven_service_integration_endpoint" "kafka_region_one_data_dog" {
  project       = aiven_project.aiven_project_kafka.project
  endpoint_name = "${local.kafka_region_one_service_name}-ddog"
  endpoint_type = "datadog"
  datadog_user_config {
    datadog_api_key = var.kafka_data_dog_api_key
  }
}

```

Running the above results in the error below:
```

 Error: Plugin did not respond

   with aiven_service_integration_endpoint.kafka_region_one_data_dog,
   on data-dog.tf line 2, in resource "aiven_service_integration_endpoint" "kafka_region_one_data_dog":
    2: resource "aiven_service_integration_endpoint" "kafka_region_one_data_dog" {

 The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
```

Stack trace from the terraform-provider-aiven_v2.1.17 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 185 [running]:
github.com/aiven/terraform-provider-aiven/aiven.ConvertTerraformUserConfigToAPICompatibleFormat(0x1bb6710, 0x8, 0xc0006da660, 0x7, 0xc000d2a101, 0xc0009c0500, 0xc000d0f6c8)
	github.com/aiven/terraform-provider-aiven/aiven/user_config.go:272 +0x1e6
github.com/aiven/terraform-provider-aiven/aiven.resourceServiceIntegrationEndpointCreate(0x1d8f598, 0xc000995980, 0xc0009c0500, 0x1b48720, 0xc00024e7e0, 0xc000d2a020, 0x146966a, 0xc00094ea40)
	github.com/aiven/terraform-provider-aiven/aiven/resource_service_integration_endpoint.go:170 +0x128
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0003aa000, 0x1d8f528, 0xc000967ac0, 0xc0009c0500, 0x1b48720, 0xc00024e7e0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:330 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003aa000, 0x1d8f528, 0xc000967ac0, 0xc0009979d0, 0xc00094ea40, 0x1b48720, 0xc00024e7e0, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000c048, 0x1d8f528, 0xc000967ac0, 0xc000b61040, 0xc000967ac0, 0x1b6dda0, 0xc0009bad00)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00094f6c0, 0x1d8f5d0, 0xc000967ac0, 0xc000997880, 0xc00094f6c0, 0xc0009bad50, 0xc0005feba0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1b6dda0, 0xc00094f6c0, 0x1d8f5d0, 0xc0009bad50, 0xc000995560, 0x0, 0x1d8f5d0, 0xc0009bad50, 0xc0009d2000, 0x4b0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00098a000, 0x1d98438, 0xc000103200, 0xc0006dcf00, 0xc00057cc30, 0x22c88c0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00098a000, 0x1d98438, 0xc000103200, 0xc0006dcf00, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00020f120, 0xc00098a000, 0x1d98438, 0xc000103200, 0xc0006dcf00)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aiven_v2.1.17 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Not sure what is causing the error?

**Comment by MojoJojo** [comment]
Alright, it seems that the error is being caused by this code:
```
resource "aiven_service_integration_endpoint" "kafka_region_one_data_dog" {
  project       = "kafka-dev"
  endpoint_name = "${local.kafka_region_one_service_name}-ddog"
  endpoint_type = "datadog"
  datadog_user_config {
    datadog_api_key = var.kafka_data_dog_api_key
  }
}
```
When I remove the above, everything works. Other resources of type `aiven_service_integration_endpoint` are also failing (i.e. prometheus endpoint). 

Is it a bug or am I missing something?

**Comment by ivan-savciuc** [comment]
@MojoJojo I do not see the `aiven_service_integration` resource in the TF code, did you just forgot to include it? Here is a good example how on how to use Data Dog integration: https://github.com/aiven/terraform-provider-aiven/blob/master/examples/datadog/service.tf 

In any case, I will be looking more closely at this issue today.

**Comment by MojoJojo** [comment]
Hi thanks for looking at this. I intentionally omitted the code as it `aiven_service_integration_endpoint` is throwing an error even with `aiven_service_integration` commented out. I have included `aiven_service_integration` in the code now. 

Thanks for the example. Busy looking at it now.

**Comment by ivan-savciuc** [comment]
I'm running the same code on my mac with the same Terraform client version but cannot reproduce this issue, and it is a weird one based on the error logs. Would you please try it with a different version of Aiven Provider?
