### ISSUE TITLE
Terraform crash with 1.0.14

### ISSUE THREAD

**Issue by danielflookovo** [aiven/terraform-provider-aiven#92]
When attempting to use the provider version 1.0.14, terraform crashes. This is using terraform 0.12.6 and the darwin binary from the releases page.

main.tf: 
```hcl
provider "aiven" {}
```

plan:
```bash
$ terraform plan
Error: Failed to instantiate provider "aiven" to obtain schema: Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.


panic: Failed to read service_user_config_schema.json: stat /srv/jenkins/workspace/terraform-provider-aiven/gopath/src/github.com/aiven/terraform-provider-aiven/aiven/templates/service_user_config_schema.json: no such file or directory
2019-08-17T15:02:05.403+0100 [DEBUG] plugin.terraform-provider-aiven_v1.0.14:
2019-08-17T15:02:05.403+0100 [DEBUG] plugin.terraform-provider-aiven_v1.0.14: goroutine 1 [running]:
2019-08-17T15:02:05.403+0100 [DEBUG] plugin.terraform-provider-aiven_v1.0.14: github.com/aiven/terraform-provider-aiven/aiven.readUserConfigJSONSchema(0x1c52b64, 0x1f, 0x1c3a9a0)
2019-08-17T15:02:05.403+0100 [DEBUG] plugin.terraform-provider-aiven_v1.0.14: 	/srv/jenkins/workspace/terraform-provider-aiven/gopath/src/github.com/aiven/terraform-provider-aiven/aiven/user_config.go:17 +0x376
2019-08-17T15:02:05.403+0100 [DEBUG] plugin.terraform-provider-aiven_v1.0.14: github.com/aiven/terraform-provider-aiven/aiven.GetUserConfigSchema(0x1c3a9a0, 0x7, 0x1c42256)
2019-08-17T15:02:05.403+0100 [DEBUG] plugin.terraform-provider-aiven_v1.0.14: 	/srv/jenkins/workspace/terraform-provider-aiven/gopath/src/github.com/aiven/terraform-provider-aiven/aiven/user_config.go:41 +0x1a0
2019-08-17T15:02:05.403+0100 [DEBUG] plugin.terraform-provider-aiven_v1.0.14: github.com/aiven/terraform-provider-aiven/aiven.init.ializers()
2019-08-17T15:02:05.403+0100 [DEBUG] plugin.terraform-provider-aiven_v1.0.14: 	/srv/jenkins/workspace/terraform-provider-aiven/gopath/src/github.com/aiven/terraform-provider-aiven/aiven/resource_service.go:139 +0x1f14
2019-08-17T15:02:05.403+0100 [DEBUG] plugin: plugin process exited: path=/Users/danielflook/.terraform.d/plugins/terraform-provider-aiven_v1.0.14 pid=78700 error="exit status 2"
2019/08/17 15:02:05 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2019/08/17 15:02:05 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2019-08-17T15:02:05.404+0100 [WARN]  plugin: plugin failed to exit gracefully



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by mteiste** [comment]
Release 1.0.15 should fix this issue

**Comment by danielflookovo** [comment]
Thanks!
